apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  labels:
    app: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: hello
          image: paulbouwer/hello-kubernetes:1.10.1
          env:
            - name: MESSAGE
              value: "This is app2"
            
