# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Generic settings
  config.vm.box = "debian/bookworm64"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.boot_timeout = 1200
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
   end

  # Pre provision script
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update && apt-get upgrade -y
    apt-get install -y curl net-tools
    echo "192.168.56.110 mlabouriS" >> /etc/hosts
    echo "192.168.56.111 mlabouriSW" >> /etc/hosts
  SHELL

  # Server
  config.vm.define "mlabouriS" do |server|
    server.vm.hostname = "mlabouriS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "mlabouriS"
    end

    server.vm.provision "shell" do |s|
      s.env = {K3S_TOKEN:ENV['P1__K3S_TOKEN']}
      s.inline = <<-SHELL
        export INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --advertise-address=192.168.56.110 --node-ip=192.168.56.110"
        curl -sfl https://get.k3s.io | sh -
      SHELL
    end
  end

  # Server Worker
  config.vm.define "mlabouriSW" do |agent|
    agent.vm.hostname = "mlabouriSW"
    agent.vm.network "private_network", ip: "192.168.56.111"
    agent.vm.provider "virtualbox" do |vb|
      vb.name = "mlabouriSW"
    end

    agent.vm.provision "shell" do |s|
      s.env = {K3S_TOKEN:ENV['P1__K3S_TOKEN']}
      s.inline = <<-SHELL 
        export INSTALL_K3S_EXEC="agent --server https://mlabouriS:6443 --node-ip=192.168.56.111"
        curl -sfl https://get.k3s.io | sh -
      SHELL
    end
  end
end
