# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER_NAME = 'mlabouriS'
SERVER_IP = '192.168.56.110'

MEM = 12288
CPU = 8
BOX = "debian/bookworm64"

Vagrant.configure("2") do |config|
  # Generic settings
  config.vm.box = BOX
  config.vm.boot_timeout = 1200
  config.vm.provider "virtualbox" do |vb|
    vb.memory = MEM
    vb.cpus = CPU
   end

  # Pre provision script
  config.vm.provision "shell", path: "scripts/prep.sh", env: {
    SERVER__NAME:SERVER_NAME,
    SERVER__IP:SERVER_IP
  }

  # Server
  config.vm.define SERVER_NAME do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provider "virtualbox" do |vb|
      vb.name = SERVER_NAME
    end

    # Run services
    server.vm.provision "shell", privileged: true, path: "scripts/run_cluster.sh"
    server.vm.provision "shell", privileged: true, path: "scripts/run_gitlab.sh", env: {
      SERVER__IP:SERVER_IP,
    }
    server.vm.provision "shell", privileged: true, path: "scripts/run_argocd.sh"
  end
end
